services:
  - type: web
    name: fandango-explorer
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
      - key: PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH
        value: "/usr/bin/chromium-browser"
    scaling:
      minInstances: 1
      maxInstances: 1
